In [ ]:
import numpy as np

# Task 1 :
empty_array = np.empty((2,2))
print("Empty Array (2x2) : ", empty_array)

# Task 2 :
ones_array = np.ones((4,2))
print("All ones array (4x2) : ", ones_array)

# Task 3 :
fill_value_array = np.full((3,3), 7)
print("Array filled with a specific value (3x3, fill=7 : ", fill_value_array)

# Task 4 :
given_array = np.array([[1,2], [3,4]])
zeros_like_array = np.zeros_like(given_array)
print("Array of zeros with the sam e shape and type as given array : ", zeros_like_array)

# Task 5 :
ones_like_array = np.ones_like(given_array)
print("Arrray of ones with the same shape and type as given array : ", ones_like_array)

# Task 6 :
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("Converted list to numPy array : ", numpy_array)


Empty Array (2x2) :  [[4.89869154e-310 0.00000000e+000]
 [9.31464664e+242 1.51298292e-152]]
All ones array (4x2) :  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array filled with a specific value (3x3, fill=7 :  [[7 7 7]
 [7 7 7]
 [7 7 7]]
Array of zeros with the sam e shape and type as given array :  [[0 0]
 [0 0]]
Arrray of ones with the same shape and type as given array :  [[1 1]
 [1 1]]
Converted list to numPy array :  [1 2 3 4]


In [ ]:
import numpy as np

# Task 1 :
array_range = np.arange(10,50)
print("Array with value ranging from 10 to 49 : ", array_range)

# Task 2 :
matrix_3x3 = np.arange(9).reshape(3,3)
print("3x3 matrix with values from 0 to 8 : ", matrix_3x3)

# Task 3 :
identity_matrix = np.eye(3)
print ("3x3 identity matrix : ", identity_matrix)

# Task 4 :
random_array = np.random.random(30) # create a random array
mean_value = random_array.mean() # calculate the mean
print("Random Array : ", random_array)
print("mean : ", mean_value)

# Task 5 :
array_10x10 = np.random.random((10,10))
min_value = array_10x10.min()
max_value = array_10x10.max()
print("10x10 array : ", array_10x10)
print("min value : ", min_value)
print("max value : ", max_value)

# Task 6 :
zero_array = np.zeros(10)
zero_array[4] = 1 # replace sth element with 1
print("modified array : ", zero_array)

# Task 7 :
arr = [1, 2, 0, 0, 4, 0]
reversed_array = arr[::-1]
print("reversed array : ", reversed_array)

# Task 8 :
array = np.ones((6,6), dtype = int)
array[1:-1, 1:-1] = 0
print("array with 1 on border and 0 on inside : ", array)

# Task 9 :
checkerboard = np.zeros((8,8), dtype = int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("checkerboard pattern : ")
print(checkerboard)


Array with value ranging from 10 to 49 :  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 matrix with values from 0 to 8 :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 identity matrix :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array :  [0.28656922 0.94925502 0.50040494 0.10412157 0.59883426 0.01849184
 0.54512434 0.15568072 0.45352426 0.02827466 0.87885994 0.74678251
 0.63569516 0.80186409 0.36287818 0.180064   0.6425577  0.21459061
 0.79704372 0.63763874 0.57641244 0.76380316 0.01336089 0.70813991
 0.16543864 0.3370176  0.95695987 0.4157041  0.16777708 0.17687033]
mean :  0.4606579830702427
10x10 array :  [[5.01370985e-01 6.68933117e-01 6.82809640e-01 8.83815811e-01
  5.34997778e-01 8.61688206e-01 2.27411649e-01 6.87484493e-01
  5.82023149e-01 2.11168085e-01]
 [1.61126696e-01 7.36966528e-01 5.06967459e-01 6.47874120e-01
  5.02145154e-01 2.16168686e-01 6.74044896e-01 1.00906567e-01
  5.50444683e-01 6.96260309e-01]
 

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1,2], [3,5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# add two arrays
sum_array = x+y
print("the sum is : ", sum_array)

# substract two arrays
diff_array = x-y
print("the difference is : ", diff_array)

# multiply array with any integer
product_array = x*2
print("array x multiplied by 2 is : ",product_array)

# find square of each element in array
square_array = x**2
print("square of each element in x is : ", square_array)

# find dot product between v and w
dot_vw = np.dot(v,w)
print("dot product between v and w is : ", dot_vw)

dot_xy = np.dot(x, y)
print("the dot product between x and y is : ", dot_xy)

# concatenation
# concatenate x and y along rows
concat_xy_rows = np.concatenate((x,y), axis = 0)
print("concatenate x and y along rows : ", concat_xy_rows)

# concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenate x and v:\n", concat_xv)
except ValueError as e:
    print("Error:", e)
# error because the arrays must be of same dimension in order to concatenate


the sum is :  [[ 6  8]
 [10 13]]
the difference is :  [[-4 -4]
 [-4 -3]]
array x multiplied by 2 is :  [[ 2  4]
 [ 6 10]]
square of each element in x is :  [[ 1  4]
 [ 9 25]]
dot product between v and w is :  219
the dot product between x and y is :  [[19 22]
 [50 58]]
concatenate x and y along rows :  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
# Task 1
import numpy as np
# Define matrices
A = np.array([[3, 4], [7, 8]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Verify A * A^-1 = I
identity = np.dot(A, A_inv)
print("A * A^-1 = ", identity)

# Task 2
# Define matrix B
B = np.array([[5, 3], [2, 1]])

# Calculate AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Check if AB != BA
print("AB =\n", AB)
print("BA =\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

# Task 3
# Calculate (AB)^T and B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))

# Verify (AB)^T = B^T * A^T
print("(AB)^T =\n", AB_T)
print("B^T * A^T =\n", BT_AT)
print("Are (AB)^T and B^T * A^T equal?", np.array_equal(AB_T, BT_AT))

# Task 4
# Define the coefficient matrix A and the constant matrix B
A_system = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_system = np.array([-1, -3, 9])

# Solve for X using inverse
A_inv_system = np.linalg.inv(A_system)
X = np.dot(A_inv_system, B_system)
print("Solution of the system [x, y, z]:", X)




A * A^-1 =  [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Are AB and BA equal? False
(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Are (AB)^T and B^T * A^T equal? True
Solution of the system [x, y, z]: [ 2.  1. -2.]
